#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ -z "$BROWSER" && "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

if [[ -z "$EDITOR" ]]; then
  export EDITOR='nano'
fi
if [[ -z "$VISUAL" ]]; then
  export VISUAL='nano'
fi
if [[ -z "$PAGER" ]]; then
  export PAGER='less'
fi

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/{,s}bin(N)
  /opt/{homebrew,local}/{,s}bin(N)
  /usr/local/{,s}bin(N)
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
if [[ -z "$LESS" ]]; then
  export LESS='-g -i -M -R -S -w -X -z-4'
fi

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if [[ -z "$LESSOPEN" ]] && (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

#
# Define a function for generating go coverage statistics for a package
# (on the command line)
#
cover-small () { 
    t="/tmp/go-cover.$$.tmp"
    go test -tags=small -coverprofile=$t $@ && go tool cover -func=$t && unlink $t
}

# add ${HOME}/bin to default path
export PATH=${HOME}/bin:${PATH}

# If running under and X-Windows session, then use the xinput command to setup
# natural scrolling for the # mouse device (for usage information, type xinput
# by itself.
if [[ ${XDG_SESSION_TYPE+x} ]]; then
    # first, determine the device ID of the mouse
    device_num="$(xinput list | grep -i mouse | awk 'match($0, /id=([0-9]+)/) { print substr($0, RSTART, RLENGTH) }' | cut -d'=' -f2)"

    # then determine the property ID used to enable natural
    # scrolling for that device
    property_num="$(xinput list-props $device_num | grep 'Natural Scrolling Enabled (' | awk 'match($0, /[0-9]+/) { print substr($0, RSTART, RLENGTH) }')"

    # and finally, ensure that property is set to '1' for
    # that device
    xinput set-prop $device_num $property_num 1
fi
