#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#export GOBIN=/usr/local/go/bin
export GOPATH=${HOME}/src/go
export PYENV_ROOT=${HOME}/.pyenv
export RBENV_ROOT=${HOME}/.rbenv
export ANACONDA_PATH=${HOME}/miniconda3
export CARGO_HOME=${HOME}/.cargo
export SNAP_PATH=${HOME}/src/go/src/github.com/intelsdi-x/snap/build
export PATH="${HOME}/bin:${GOPATH}/bin:${PYENV_ROOT}/bin:${RBENV_ROOT}/bin:${ANACONDA_PATH}/bin:${CARGO_HOME}/bin:/usr/local/bin:/usr/local/go/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"

# set the default editor to vi rather than nano
export EDITOR=vi

# ack alias
type -p ack > /dev/null && alias ack="ack --pager='less -R'"

# alias for 'dirs -v'
alias dh='dirs -v'

# alias to open files from the command-line
alias open='xdg-open'

# alias to restart cinnamon
alias restart-cinnamon="${HOME}/bin/restart-cinnamon.sh"

# initialize rbenv and pyenv (if the corresponding commands exist
if command -v rbenv 1>/dev/null 2>&1; then
    eval "$(rbenv init -)"
fi
if command -v pyenv 1>/dev/null 2>&1; then
    eval "$(pyenv init -)"
fi

# alias python to run python3
#alias python=python3
#alias pip=pip3

# brew package update
#alias brew_fresh='brew update && brew upgrade --all; brew cleanup; brew cask cleanup; brew doctor'

# setup aliases to manage process of setting and unsetting
# the https_proxy environment variable
#alias set-iag-web-proxy='source ${HOME}/bin/set-iag-web-proxy.sh'
#alias unset-iag-web-proxy='source ${HOME}/bin/unset-iag-web-proxy.sh'

# and change the color used to display directories to a more visible blue
#
#   Note that the LSCOLORS value shown below is encoded using a scheme where
#   the first letter is the foreground, the second the background, the values
#   are taken from this list of ANSI color codes:
#
#     a black
#     b red
#     c green
#     d brown
#     e blue
#     f magenta
#     g cyan
#     h light grey
#     A bold black, usually shows up as dark grey
#     B bold red
#     C bold green
#     D bold brown, usually shows up as yellow
#     E bold blue
#     F bold magenta
#     G bold cyan
#     H bold light grey; looks like bright white
#     x default foreground or background
#
# and the order of attributes is as follows:
#
#     1. directory
#     2. symbolic link
#     3. socket
#     4. pipe
#     5. executable
#     6. block special
#     7. character special
#     8. executable with setuid bit set
#     9. executable with setgid bit set
#     10. directory writable to others, with sticky bit
#     11. directory writable to others, without sticky bit
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

# and ensure that the same color scheme is used for tab expansion listings
zstyle ':completion:*:default' list-colors ${(s.:.)LSCOLORS}

# if the kubectl command exists
if command -v kubectl 1>/dev/null 2>&1; then
    # then setup Kubernetes config file variable
    KUBECONFIG=/home/tjmcs/.kube/config
    # setup autocompletion for the kubectl command
    source <(kubectl completion zsh)
fi
